mysite/myapp/urls.py
from django.urls import path
from myapp.views import index, indexItem

app_name = "myapp"

urlpatterns = [
    # http://127.0.0.1:8000/myapp/
    path("", index),
    path("<int:my_id>/", indexItem, name="detail"),
    # http://127.0.0.1:8000/myapp/hello/
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("myapp/", include("myapp.urls", namespace="myapp")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')
    
    def __str__(self):
        return self.name

mysite/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product


def index(request):
    items = Product.objects.all()
    context = {
        'items': items
    }
    return render(request, "myapp/index.html", context)


def indexItem(request, my_id):
    item = Product.objects.get(id=my_id)
    context = {
        'item': item
    }
    return render(request, "myapp/detail.html", context=context)

mysite/myapp/templates/myapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}" />
    <title>Document</title>
  </head>
  <body>
    {% include 'myapp/navbar.html' %}
    {% block content %}
      TEXT
    {% endblock content %}
  </body>
</html>

mysite/myapp/templates/myapp/detail.html
{% extends "myapp/base.html"%}

{% block content %}
<h1>
    This detail page for : {{item.name}}
</h1>
{% endblock content %}

mysite/myapp/templates/myapp/index.html
{% extends "myapp/base.html"%} {% block content %}

<div
  class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-3"
>
  {% for item in items %}
  <a href="{% url 'myapp:detail' item.id %} ">
    <div class="rounded overflow-hidden shadow-lg">
      <img class="w-full" src="{{item.image.url}}" alt="" />
      <div class="px-6 py-4">
        <p class="font-bold text-xl mb-2">{{item.name}}</p>
        <p class="font-bold text-xl text-green-500 mb-2">${{item.price}}</p>
        <p class="text-gray-700 text-base">{{item.description}}</p>
      </div>
    </div>
  </a>
  {% endfor %}
</div>

{% endblock content %}

mysite/myapp/templates/myapp/navbar.html
{% load static %}
<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
      <div class="flex justify-between">
        <div class="flex space-x-7">
          <div>
            <a href="#" class="flex items-center px-2 py-4">
              <img
                class="h-8 w-8"
                src="{% static 'myapp/images/shop.png' %}"
                alt="logo"
              />
              <span class="text-gray-500 font-semibold text-xl">Pro Shop</span>
            </a>
          </div>
          <div class="items-center flex space-x-1">
            <a
              href="#"
              class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500"
              >Home</a
            >
            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">About</a>
            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Place</a>
          </div>
        </div>
      </div>
    </div>
  </nav>